In [2]:
import torch

In [3]:
x = torch.randn(3, requires_grad=True)
print(x)

tensor([ 0.9834,  0.5204, -0.2948], requires_grad=True)


In [4]:
# both are used to avoid computing the gradient for the var.

x.requires_grad_(False) # underscore: modify variable in place.
x.detach()

tensor([ 0.9834,  0.5204, -0.2948])

In [6]:
#another method to avoid computing gradient.
with torch.no_grad():
    y = x + 2
    print(y)

tensor([2.9834, 2.5204, 1.7052])


In [5]:
print(x)

tensor([ 0.9834,  0.5204, -0.2948])


# Training loop

In [11]:
weights = torch.ones(4, requires_grad = True)

for epoch in range(3):
    model_output = (weights * 3).sum()
    
    model_output.backward()
    # every time this is called the previous gradients are accumulated, they should be emptied.
    
    print(weights.grad)
    
    #emptie gradients:
    weights.grad.zero_()

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
